
message_infos = {
    'reset-pwd' : ' Congratulations! Your password has been reset. Please login with your new password.',
    'reset-pwd-zh' : '恭喜，密码重置成功；请使用新密码登录',
    'reset-pay-pwd' : ' Congratulations! Your payment password has been reset.',
    'reset-pay-pwd-zh' : '恭喜，支付密码重置成功',
    'buy-self' : 'You cannot buy your own goods.',
    'buy-self-zh': '您不能购买自己挂售的商品哦',
    'com-err': ' Abnormal commodity. The administrator is dealing with the problem. ',
    'com-err-zh': '商品异常，管理员正在处理',
    'buy-success': ' Congratulations! Your transaction is successful. Please check.',
    'buy-success-zh': '恭喜！交易成功，请注意查收',
    'money': ' Insufficient balance. Please top up.',
    'money-zh': '余额不足，请充值',
    'pay-pwd-err': ' Pay-password is wrong. Please try again.',
    'pay-pwd-err-zh': '支付密码错误，请重新填写',
    'user-err': 'Error! The account is abnormal, please try again.',
    'user-err-zh': '账户异常，交易出现错误，请重试',
    'recharge-err': 'Incomplete top-up(s)',
    'recharge-err-zh': '您有未完成的充值订单',
    'take-success': 'Congratulations! Successful withdrawal.',
    'take-success-zh': '恭喜您！提币成功',
    'take-num-err': 'Your withdrawal is beyond the limits. ',
    'take-num-err-zh': '提币数量超出范围',
    'adress-err': 'Please ensure your receiving address is correct.',
    'adress-err-zh': '请填写正确的提币地址',
    'take-amount-err': 'Please ensure your amount is correct.',
    'take-amount-err-zh': '请填写正确的提币数量',
    'take-adress-err': 'Please enter your receiving address.',
    'take-adress-err-zh': '请填写提币地址',
    'sell-success': 'Congratulations! Already on sale.',
    'sell-success-zh': '恭喜您！已在挂售',
    'stop-sell-success': 'Your selling has been stopped.',
    'stop-sell-success-zh': '已完成下架操作',
    'exchange-success': 'Congratulations! Successful Exchange.',
    'exchange-success-zh': '恭喜您！兑换成功',
    'opera-err' : 'Illegal operation, please order again.',
    'opera-err-zh' : '违规操作，请重新下单',
    'num-err' : 'You can only buy one nft commodity at a time',
    'num-err-zh' : 'ntf商品每次只能购买一个哦',
    'num-warn' : 'Your purchase is beyond the amount of stock.',
    'num-warn-zh' : '当前购买数量超出库存啦',
    'distr-err' : 'Error! The distribution quantity is wrong.',
    'distr-err-zh' : '分配数量出现错误了',
    'distr-success' : 'Congratulations! Successful asset distribution!',
    'distr-success-zh' : '恭喜！分配资产成功'
}

